# what is tensor
A tensor is a mathematical object that is a generalization of scalars, vectors, and matrices. Tensors are used in various fields, including physics and engineering, to represent data with multiple dimensions. In the context of deep learning and PyTorch, tensors are the primary data structure used to store and manipulate data.

Tensors can be thought of as n-dimensional arrays, where:
- A 0-dimensional tensor is a scalar (e.g., a single number).
- A 1-dimensional tensor is a vector (e.g., a list of numbers).
- A 2-dimensional tensor is a matrix (e.g., a table of numbers).
- Higher-dimensional tensors can represent more complex data structures (e.g., a 3D tensor could represent a color image with width, height, and color channels).

PyTorch provides a flexible and efficient way to work with tensors, allowing for easy manipulation, mathematical operations, and integration with GPU acceleration for deep learning tasks.

In [9]:
input_value = [1, 2, 3,'4']

sum(input_value)


TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [11]:
import numpy as np

a = np.array([1, 2, 3,'rahul'], dtype=np.float64)
sum(a)

ValueError: could not convert string to float: 'rahul'

In [4]:
import torch as tc

v = tc.tensor([1, 2, 3, 4, 5, 6])
print('v:', v)
print('dtype:', v.dtype)
print('shape:', v.shape)

# indexing
print('indexing:', v[0], v[1], v[2])

# slicing
print('slice 1:4:', v[1:4])
print('slice :3:', v[:3])
print('slice 3::', v[3:])


v: tensor([1, 2, 3, 4, 5, 6])
dtype: torch.int64
shape: torch.Size([6])
indexing: tensor(1) tensor(2) tensor(3)
slice 1:4: tensor([2, 3, 4])
slice :3: tensor([1, 2, 3])
slice 3:: tensor([4, 5, 6])


In [4]:
import numpy as np
input_array = [1, 2, 3,'2']
np.array(input_array,dtype=np.float32)

array([1., 2., 3., 2.], dtype=float32)

In [14]:
f = tc.FloatTensor([1, 2, 3, 4, 5, 6])
print('f:', f)
print('dtype:', f.dtype)
print('shape:', f.shape)
print('ndimension:', f.ndimension())
# A 1-D tensor is a vector (no separate row/column dimension).


f: tensor([1., 2., 3., 4., 5., 6.])
dtype: torch.float32
shape: torch.Size([6])
ndimension: 1


In [18]:
a

array([1., 2., 3., 4.])

In [ ]:
# f.view(4, 2)
a = np.array([1,2,3,4,5,6])
a = a.reshape(2, 3) #here 2 means the number of rows and 3 means the number of columns
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(v)
v.view(4,2) # here 4 means the number of rows and 2 means the number of columns

tensor([1, 2, 3, 4, 5, 6])


RuntimeError: shape '[4, 2]' is invalid for input of size 6

In [11]:
print('v.view(6, 1):', v.view(6, 1)) # here 6 means 6 rows, 1 column
# 6 rows, 1 column -> 2D tensor
print('v.view(2, 3):', v.view(2, 3))
print('v.view(3, 2):', v.view(3, 2))
print('v.view(3, -1):', v.view(3, -1))


v.view(6, 1): tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])
v.view(2, 3): tensor([[1, 2, 3],
        [4, 5, 6]])
v.view(3, 2): tensor([[1, 2],
        [3, 4],
        [5, 6]])
v.view(3, -1): tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [15]:
# you can convert numpy arr to tensor
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])
t = tc.from_numpy(a)
print('t:', t)
print('shape:', t.shape)
print('ndimension:', t.ndimension())


t: tensor([1, 2, 3, 4, 5, 6])
shape: torch.Size([6])
ndimension: 1


# Conclusion:
In this notebook, we covered the basics of PyTorch tensors, including their creation, manipulation, and conversion from NumPy arrays. We explored various tensor operations such as indexing, slicing, and reshaping, as well as how to obtain tensor properties like shape and dimension. Understanding these concepts is crucial for effectively working with tensors in deep learning applications.

